# Generated by Django 3.1.2 on 2020-10-31 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='company_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='company_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=10)),
                ('description_company', models.TextField(max_length=255)),
                ('logo_company', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('id_address', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.company_address')),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='job_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_job_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='profile_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('cv', models.FileField(upload_to='')),
                ('id_user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.account_user')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=255)),
                ('offer_salary', models.IntegerField(default=0)),
                ('id_address', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.company_address')),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.company_info')),
                ('id_job_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.job_type')),
                ('id_location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.location')),
            ],
        ),
        migrations.CreateModel(
            name='districst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_district', models.CharField(max_length=255)),
                ('id_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.city')),
            ],
        ),
        migrations.AddField(
            model_name='company_info',
            name='id_country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.country'),
        ),
        migrations.AddField(
            model_name='company_address',
            name='id_district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.districst'),
        ),
    ]
