# Generated by Django 3.1.2 on 2020-11-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_user',
            name='cv',
            field=models.FileField(upload_to='cv/%Y/%m/%d/'),
        ),
    ]
