# Generated by Django 3.1.2 on 2020-11-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20201102_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_info',
            name='email_company',
            field=models.CharField(default='mail', max_length=255),
        ),
    ]
