# Generated by Django 3.1.2 on 2020-11-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_company_info_email_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_info',
            name='back_ground_company',
            field=models.URLField(default='https://cdn.itviec.com/photos/45720/processed_headline_photo/viettel-group-tuyen-dung-viec-lam-IT-headline_photo-1512381.jpg?H43eaiySzXeJcgwxGr8DYN29'),
        ),
    ]
