# Generated by Django 3.1.2 on 2020-11-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20201106_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_info',
            name='description_company',
            field=models.TextField(max_length=10000),
        ),
    ]
