# Generated by Django 3.1.2 on 2020-11-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20201106_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
