# Generated by Django 3.1.2 on 2020-11-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20201106_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_info',
            name='logo_company',
            field=models.URLField(),
        ),
    ]
