# Generated by Django 3.1.2 on 2020-11-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20201106_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requirement',
            field=models.TextField(default='type requirement in here', max_length=10000),
        ),
    ]
